# Generated by Django 4.1.7 on 2023-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.CharField(),
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='user',
        ),
    ]
